#
# SPDX-FileCopyrightText: Copyright 2024-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0
#

[versions]

activityCompose = "1.9.3"
agp = "8.3.2"
composeBom = "2024.12.01"
coreKtx = "1.12.0"
composeUi = "1.7.0"
espressoCore = "3.6.1"
glideCompose = "1.0.0-alpha.5"
googleAccompanistPermissions = "0.34.0"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.0"
kotlinxSerializationJson = "1.6.0"
lifecycleRuntimeKtx = "2.8.6"
mockitoAndroid = "5.8.0"
androidxTestRules = "1.5.0"
navigationRuntimeKtx = "2.8.3"
navigationCompose = "2.8.3"
navigationTesting = "2.8.3"
okhttp3 = "4.12.0"
retrofit2 = "2.9.0"

[libraries]

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-testing = { group = "androidx.navigation", name="navigation-testing", version.ref = "navigationTesting" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref="composeUi" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref="composeUi" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref="composeUi" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref="composeUi" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref="composeUi" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref="composeUi" }
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "googleAccompanistPermissions" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideCompose" }

# Retrofit
squareup-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
squareup-retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
retrofit = [
    "squareup-retrofit2",
    "squareup-retrofit2-converter-gson",
    "squareup-okhttp3-logging-interceptor",
]
